### ISSUE TITLE
Error Inflating class IconTextView

### ISSUE THREAD

**Issue by hth** [JoanZapata/android-iconify#144]
Can someone please point out why I am getting this error. 

error after migrating from 1.x to 2.x.
BuildToolVersion 23.0.2

        FATAL EXCEPTION: main
        Process: com.xxx.xxx, PID: 13967
        java.lang.RuntimeException: Unable to start activity ComponentInfo{x.x.x.ListActivity}: android.view.InflateException: Binary XML file line #23: Binary XML file line #14: Error inflating class IconTextView
           at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2416)
           at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
           at android.app.ActivityThread.-wrap11(ActivityThread.java)
           at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
           at android.os.Handler.dispatchMessage(Handler.java:102)
           at android.os.Looper.loop(Looper.java:148)
           at android.app.ActivityThread.main(ActivityThread.java:5417)
           at java.lang.reflect.Method.invoke(Native Method)
           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
        Caused by: android.view.InflateException: Binary XML file line #23: Binary XML file line #14: Error inflating class IconTextView
           at android.view.LayoutInflater.inflate(LayoutInflater.java:539)
           at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
           at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
           at com.android.internal.policy.PhoneWindow.setContentView(PhoneWindow.java:393)
           at android.app.Activity.setContentView(Activity.java:2172)
           at com.x.x.onCreate(xxxListActivity.java:80)
           at android.app.Activity.performCreate(Activity.java:6251)
           at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)
           at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369)
           at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476) 
           at android.app.ActivityThread.-wrap11(ActivityThread.java) 
           at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344) 
           at android.os.Handler.dispatchMessage(Handler.java:102) 
           at android.os.Looper.loop(Looper.java:148) 
           at android.app.ActivityThread.main(ActivityThread.java:5417) 
           at java.lang.reflect.Method.invoke(Native Method) 
           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
        Caused by: android.view.InflateException: Binary XML file line #14: Error inflating class IconTextView

**Comment by JoanZapata** [comment]
Did you use the fully qualified name in your layout file?

```xml
<com.joanzapata.iconify.widget.IconTextView
   ... />
```

**Comment by hth** [comment]
You were spot on. That was it. Thank you for your help. Awesome Library. 
Marking as closed.
