### ISSUE TITLE
Crash  ParsingUtil.java line 32 

### ISSUE THREAD

**Issue by abdullahumer** [JoanZapata/android-iconify#145]
I'm getting a crash in Crashlytics report and the impact is going high.

```
Fatal Exception: java.lang.NullPointerException
       at android.text.SpannableStringBuilder.<init>(SpannableStringBuilder.java:44)
       at com.joanzapata.iconify.internal.ParsingUtil.parse(ParsingUtil.java:32)
       at com.joanzapata.iconify.Iconify.compute(Iconify.java:59)
       at com.joanzapata.iconify.widget.IconTextView.setText(IconTextView.java:34)
       at android.widget.TextView.setText(TextView.java:3780)
       at com.haraj.app.backend.HJMessageListAdapter.getView(HJMessageListAdapter.java:72)
       at android.widget.AbsListView.obtainView(AbsListView.java:2306)
       at android.widget.ListView.measureHeightOfChildren(ListView.java:1263)
       at android.widget.ListView.onMeasure(ListView.java:1175)
       at android.view.View.measure(View.java:16581)
       at android.widget.RelativeLayout.measureChild(RelativeLayout.java:689)
       at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:473)
       at android.view.View.measure(View.java:16581)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5140)
       at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
       at android.view.View.measure(View.java:16581)
       at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:719)
       at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:455)
       at android.view.View.measure(View.java:16581)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5140)
       at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
       at android.view.View.measure(View.java:16581)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5140)
       at com.android.internal.widget.ActionBarOverlayLayout.onMeasure(ActionBarOverlayLayout.java:327)
       at android.view.View.measure(View.java:16581)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5140)
       at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
       at com.android.internal.policy.impl.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2423)
       at android.view.View.measure(View.java:16581)
       at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:1961)
       at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1157)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1339)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1044)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5896)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:761)
       at android.view.Choreographer.doCallbacks(Choreographer.java:574)
       at android.view.Choreographer.doFrame(Choreographer.java:544)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:747)
       at android.os.Handler.handleCallback(Handler.java:733)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:136)
       at android.app.ActivityThread.main(ActivityThread.java:5118)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:605)
       at dalvik.system.NativeStart.main(NativeStart.java)
```

Any help?

**Comment by JoanZapata** [comment]
It seems you're doing `setText(null)` directly or indirectly on your `IconTextView`.
It shouldn't crash, i'll fix it. In the meanwhile, as a workaround please use `setText("")` instead.

**Comment by abdullahumer** [comment]
In another place I'm getting a crash like this:

```
Fatal Exception: java.lang.StringIndexOutOfBoundsException: length=10; regionStart=10; regionLength=-11
       at java.lang.String.startEndAndLength(String.java:593)
       at java.lang.String.substring(String.java:1474)
       at com.joanzapata.iconify.internal.ParsingUtil.recursivePrepareSpannableIndexes(ParsingUtil.java:98)
       at com.joanzapata.iconify.internal.ParsingUtil.recursivePrepareSpannableIndexes(ParsingUtil.java:115)
       at com.joanzapata.iconify.internal.ParsingUtil.recursivePrepareSpannableIndexes(ParsingUtil.java:180)
       at com.joanzapata.iconify.internal.ParsingUtil.parse(ParsingUtil.java:33)
       at com.joanzapata.iconify.Iconify.compute(Iconify.java:59)
       at com.joanzapata.iconify.widget.IconButton.setText(IconButton.java:34)
       at android.widget.TextView.setText(TextView.java:3344)
       at com.haraj.app.backend.HJAdDetailViewAdapter.getView(HJAdDetailViewAdapter.java:375)
       at android.widget.AbsListView.obtainView(AbsListView.java:2452)
       at android.widget.ListView.makeAndAddView(ListView.java:1780)
       at android.widget.ListView.fillDown(ListView.java:678)
       at android.widget.ListView.fillFromTop(ListView.java:738)
       at android.widget.ListView.layoutChildren(ListView.java:1617)
       at android.widget.AbsListView.onLayout(AbsListView.java:2282)
       at android.view.View.layout(View.java:11420)
       at android.view.ViewGroup.layout(ViewGroup.java:4238)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:431)
       at android.view.View.layout(View.java:11420)
       at android.view.ViewGroup.layout(ViewGroup.java:4238)
       at android.support.v4.view.ViewPager.onLayout(ViewPager.java:1627)
       at android.view.View.layout(View.java:11420)
       at android.view.ViewGroup.layout(ViewGroup.java:4238)
       at android.widget.RelativeLayout.onLayout(RelativeLayout.java:925)
       at android.view.View.layout(View.java:11420)
       at android.view.ViewGroup.layout(ViewGroup.java:4238)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:431)
       at android.view.View.layout(View.java:11420)
       at android.view.ViewGroup.layout(ViewGroup.java:4238)
       at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1644)
       at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1502)
       at android.widget.LinearLayout.onLayout(LinearLayout.java:1415)
       at android.view.View.layout(View.java:11420)
       at android.view.ViewGroup.layout(ViewGroup.java:4238)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:431)
       at android.view.View.layout(View.java:11420)
       at android.view.ViewGroup.layout(ViewGroup.java:4238)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1671)
       at android.view.ViewRootImpl.handleMessage(ViewRootImpl.java:2628)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:137)
       at android.app.ActivityThread.main(ActivityThread.java:4517)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:511)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:993)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:760)
       at dalvik.system.NativeStart.main(NativeStart.java)
```

I checked my code at `com.haraj.app.backend.HJAdDetailViewAdapter.getView(HJAdDetailViewAdapter.java:375)`

and its:
`buttonUsername.setText("\u200F" + "{fa-user 16sp @color/hj_color_blue}" + "  " + ad.getAuthorName());`

Even if `ad.getAuthorName()` is `null`, the complete string should never be `null`.

**Comment by JoanZapata** [comment]
It's a different one, can you open a new issue for it?

**Comment by abdullahumer** [comment]
created a new issue #146

**Comment by JoanZapata** [comment]
Thanks!
