### ISSUE TITLE
crash ParsingUtil.java:98

### ISSUE THREAD

**Issue by abdullahumer** [JoanZapata/android-iconify#146]
```
Fatal Exception: java.lang.StringIndexOutOfBoundsException: length=10; regionStart=10; regionLength=-11
       at java.lang.String.startEndAndLength(String.java:593)
       at java.lang.String.substring(String.java:1474)
       at com.joanzapata.iconify.internal.ParsingUtil.recursivePrepareSpannableIndexes(ParsingUtil.java:98)
       at com.joanzapata.iconify.internal.ParsingUtil.recursivePrepareSpannableIndexes(ParsingUtil.java:115)
       at com.joanzapata.iconify.internal.ParsingUtil.recursivePrepareSpannableIndexes(ParsingUtil.java:180)
       at com.joanzapata.iconify.internal.ParsingUtil.parse(ParsingUtil.java:33)
       at com.joanzapata.iconify.Iconify.compute(Iconify.java:59)
       at com.joanzapata.iconify.widget.IconButton.setText(IconButton.java:34)
       at android.widget.TextView.setText(TextView.java:3344)
       at com.haraj.app.backend.HJAdDetailViewAdapter.getView(HJAdDetailViewAdapter.java:375)
       at android.widget.AbsListView.obtainView(AbsListView.java:2452)
       at android.widget.ListView.makeAndAddView(ListView.java:1780)
       at android.widget.ListView.fillDown(ListView.java:678)
       at android.widget.ListView.fillFromTop(ListView.java:738)
       at android.widget.ListView.layoutChildren(ListView.java:1617)
       at android.widget.AbsListView.onLayout(AbsListView.java:2282)
       at android.view.View.layout(View.java:11420)
       at android.view.ViewGroup.layout(ViewGroup.java:4238)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:431)
       at android.view.View.layout(View.java:11420)
       at android.view.ViewGroup.layout(ViewGroup.java:4238)
       at android.support.v4.view.ViewPager.onLayout(ViewPager.java:1627)
       at android.view.View.layout(View.java:11420)
       at android.view.ViewGroup.layout(ViewGroup.java:4238)
       at android.widget.RelativeLayout.onLayout(RelativeLayout.java:925)
       at android.view.View.layout(View.java:11420)
       at android.view.ViewGroup.layout(ViewGroup.java:4238)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:431)
       at android.view.View.layout(View.java:11420)
       at android.view.ViewGroup.layout(ViewGroup.java:4238)
       at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1644)
       at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1502)
       at android.widget.LinearLayout.onLayout(LinearLayout.java:1415)
       at android.view.View.layout(View.java:11420)
       at android.view.ViewGroup.layout(ViewGroup.java:4238)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:431)
       at android.view.View.layout(View.java:11420)
       at android.view.ViewGroup.layout(ViewGroup.java:4238)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1671)
       at android.view.ViewRootImpl.handleMessage(ViewRootImpl.java:2628)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:137)
       at android.app.ActivityThread.main(ActivityThread.java:4517)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:511)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:993)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:760)
       at dalvik.system.NativeStart.main(NativeStart.java)
```

I checked my code at `com.haraj.app.backend.HJAdDetailViewAdapter.getView(HJAdDetailViewAdapter.java:375)`

and its:
`buttonUsername.setText("\u200F" + "{fa-user 16sp @color/hj_color_blue}" + "  " + ad.getAuthorName());`

Even if `ad.getAuthorName()` is `null`, the complete string should never be `null`.

**Comment by RaduPrescura** [comment]
@JoanZapata I don't think the fix did it as endIndex will be 0 by the time you do the` if (endIndex == -1) return; ` check as you are adding +1 before the if statement. 

Thank you for this awesome library
