### ISSUE TITLE
Crash IconTextView Binary XML file line #7

### ISSUE THREAD

**Issue by abdullahumer** [JoanZapata/android-iconify#171]
```
Fatal Exception: android.view.InflateException: Binary XML file line #7: Error inflating class com.joanzapata.iconify.widget.IconTextView
       at android.view.LayoutInflater.createView(LayoutInflater.java:606)
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:680)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:739)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:489)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:396)
       at com.haraj.app.backend.HJNotesAdapter.getView(HJNotesAdapter.java:70)
       at android.widget.AbsListView.obtainView(AbsListView.java:2216)
       at android.widget.ListView.measureHeightOfChildren(ListView.java:1244)
       at android.widget.ListView.onMeasure(ListView.java:1155)
       at android.view.View.measure(View.java:12863)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:4704)
       at android.widget.FrameLayout.onMeasure(FrameLayout.java:293)
       at android.view.View.measure(View.java:12863)
       at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:594)
       at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:376)
       at android.view.View.measure(View.java:12863)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:4704)
       at android.widget.FrameLayout.onMeasure(FrameLayout.java:293)
       at android.view.View.measure(View.java:12863)
       at android.widget.LinearLayout.measureVertical(LinearLayout.java:812)
       at android.widget.LinearLayout.onMeasure(LinearLayout.java:553)
       at android.view.View.measure(View.java:12863)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:4704)
       at android.widget.FrameLayout.onMeasure(FrameLayout.java:293)
       at com.android.internal.policy.impl.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2256)
       at android.view.View.measure(View.java:12863)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1197)
       at android.view.ViewRootImpl.handleMessage(ViewRootImpl.java:2585)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:137)
       at android.app.ActivityThread.main(ActivityThread.java:4507)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:511)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:790)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:557)
       at dalvik.system.NativeStart.main(NativeStart.java)
Caused by java.lang.reflect.InvocationTargetException
       at java.lang.reflect.Constructor.constructNative(Constructor.java)
       at java.lang.reflect.Constructor.newInstance(Constructor.java:417)
       at android.view.LayoutInflater.createView(LayoutInflater.java:586)
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:680)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:739)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:489)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:396)
       at com.haraj.app.backend.HJNotesAdapter.getView(HJNotesAdapter.java:70)
       at android.widget.AbsListView.obtainView(AbsListView.java:2216)
       at android.widget.ListView.measureHeightOfChildren(ListView.java:1244)
       at android.widget.ListView.onMeasure(ListView.java:1155)
       at android.view.View.measure(View.java:12863)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:4704)
       at android.widget.FrameLayout.onMeasure(FrameLayout.java:293)
       at android.view.View.measure(View.java:12863)
       at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:594)
       at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:376)
       at android.view.View.measure(View.java:12863)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:4704)
       at android.widget.FrameLayout.onMeasure(FrameLayout.java:293)
       at android.view.View.measure(View.java:12863)
       at android.widget.LinearLayout.measureVertical(LinearLayout.java:812)
       at android.widget.LinearLayout.onMeasure(LinearLayout.java:553)
       at android.view.View.measure(View.java:12863)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:4704)
       at android.widget.FrameLayout.onMeasure(FrameLayout.java:293)
       at com.android.internal.policy.impl.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2256)
       at android.view.View.measure(View.java:12863)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1197)
       at android.view.ViewRootImpl.handleMessage(ViewRootImpl.java:2585)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:137)
       at android.app.ActivityThread.main(ActivityThread.java:4507)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:511)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:790)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:557)
       at dalvik.system.NativeStart.main(NativeStart.java)
Caused by java.lang.ArrayIndexOutOfBoundsException: length=2; index=2
       at android.graphics.Typeface.setTypefaceFlipFont(Typeface.java:358)
       at android.graphics.Typeface.getTypefaceFlipFont(Typeface.java:178)
       at android.widget.TextView.setTypefaceByIndex(TextView.java:1335)
       at android.widget.TextView.<init>(TextView.java:1228)
       at android.widget.TextView.<init>(TextView.java:566)
       at com.joanzapata.iconify.widget.IconTextView.<init>(IconTextView.java:19)
       at java.lang.reflect.Constructor.constructNative(Constructor.java)
       at java.lang.reflect.Constructor.newInstance(Constructor.java:417)
       at android.view.LayoutInflater.createView(LayoutInflater.java:586)
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:680)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:739)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:489)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:396)
       at com.haraj.app.backend.HJNotesAdapter.getView(HJNotesAdapter.java:70)
       at android.widget.AbsListView.obtainView(AbsListView.java:2216)
       at android.widget.ListView.measureHeightOfChildren(ListView.java:1244)
       at android.widget.ListView.onMeasure(ListView.java:1155)
       at android.view.View.measure(View.java:12863)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:4704)
       at android.widget.FrameLayout.onMeasure(FrameLayout.java:293)
       at android.view.View.measure(View.java:12863)
       at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:594)
       at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:376)
       at android.view.View.measure(View.java:12863)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:4704)
       at android.widget.FrameLayout.onMeasure(FrameLayout.java:293)
       at android.view.View.measure(View.java:12863)
       at android.widget.LinearLayout.measureVertical(LinearLayout.java:812)
       at android.widget.LinearLayout.onMeasure(LinearLayout.java:553)
       at android.view.View.measure(View.java:12863)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:4704)
       at android.widget.FrameLayout.onMeasure(FrameLayout.java:293)
       at com.android.internal.policy.impl.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2256)
       at android.view.View.measure(View.java:12863)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1197)
       at android.view.ViewRootImpl.handleMessage(ViewRootImpl.java:2585)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:137)
       at android.app.ActivityThread.main(ActivityThread.java:4507)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:511)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:790)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:557)
       at dalvik.system.NativeStart.main(NativeStart.java)

```

**Comment by abdullahumer** [comment]
Version:
`compile 'com.joanzapata.iconify:android-iconify-fontawesome:2.2.2'`
