### ISSUE TITLE
Drawables returning as null

### ISSUE THREAD

**Issue by MatthewBooth** [JoanZapata/android-iconify#99]
Using the below code:

```Java
menuItem.setIcon(new IconDrawable(this, Iconify.IconValue.fa_refresh)
                .colorRes(typedArray.getResourceId(0, Color.BLACK))
                .sizeDp(16));
```

As of 1.0.10 for some reason this returns null and throws an exception. If I replace that with a resource id (R.drawable.something_here) the icon (something_here) shows. So I've narrowed this down exactly to Iconify. The same code was working before 1.0.10, but I was forced to update to 1.0.10 due to a missing font, for whatever reason that happened.

**Comment by MatthewBooth** [comment]
Where are my manners, here's a snippet of the logcat

```
 java.lang.NullPointerException: Attempt to invoke virtual method 'android.graphics.drawable.Drawable android.graphics.drawable.Drawable$ConstantState.newDrawable()' on a null object reference
            at android.support.design.internal.NavigationMenuItemView.setIcon(NavigationMenuItemView.java:113)
            at android.support.design.internal.NavigationMenuItemView.initialize(NavigationMenuItemView.java:72)
            at android.support.design.internal.NavigationMenuPresenter$NavigationMenuAdapter.getView(NavigationMenuPresenter.java:305)
            at android.widget.HeaderViewListAdapter.getView(HeaderViewListAdapter.java:220)
            at android.widget.AbsListView.obtainView(AbsListView.java:2347)
            at android.widget.ListView.makeAndAddView(ListView.java:1864)
```

**Comment by MatthewBooth** [comment]
The typedArray works fine, btw, also. Just ruling that out.

**Comment by MatthewBooth** [comment]
Nevermind, this was fixed by reverting to support libraries: 22.2.0. My bad.

**Comment by JoanZapata** [comment]
#93 for reference.

**Comment by MatthewBooth** [comment]
How on earth did I miss #93 :/

Cheers!
